name: Code analysis
'on':
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.5'
          channel: 'stable'
      - run: flutter --version

      - name: Cache pub dependencies
        uses: actions/cache@v2
        with:
          path: ${{ env.FLUTTER_HOME }}/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: ${{ runner.os }}-pub-

      - name: Run clean Domain
        run: |
          cd conges_domain  
          flutter clean

      - name: Download pub dependencies Domain
        run: |
          cd conges_domain  
          flutter pub get

      - name: Run analyzer Domain
        run: |
          cd conges_domain  
          flutter analyze

      - name: Run tests Domain
        run: |
          cd conges_domain  
          flutter test --coverage

      - name: Run clean UI
        run: |
          cd conges_ui  
          flutter clean

      - name: Download pub dependencies UI
        run: |
          cd conges_ui  
          flutter pub get

      - name: Run tests UI
        run: |
          cd conges_ui  
          flutter test --coverage

      - name: Build Web App
        run: |
          cd conges_ui  
          flutter build web --base-href=/ --release